### ISSUE TITLE
coroutine object is not iterable

### ISSUE THREAD

**Issue by MEDumont** [antoinebou12/hass_renpho#11]
Receiving this error upon a fresh installation with latest version of HomeAssistant. Looks like the setup_platoform function is setup to run synchronously, but it is using a coroutine: sensor_entities.

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/renpho/sensor.py", line 717, in setup_platform
    add_entities(sensor_entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 433, in _schedule_add_entities
    list(new_entities),
    ^^^^^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not iterable```

**Comment by antoinebou12** [comment]
Should be fix v2.0.2. Please confirm

**Comment by MEDumont** [comment]
The coroutine error is gone. Still unable to get data due to these errors:
![image](https://github.com/antoinebou12/hass_renpho/assets/7817161/1f7b0005-b3d4-4ff4-8dba-bcdaabf7b2a4)

**Comment by antoinebou12** [comment]
https://github.com/antoinebou12/hass_renpho/releases/tag/v.3.0.1
